openapi: 3.0.3

info:
  title: World Cup Predictions API
  version: 1.0.0
  
components:
  schemas:
    Match:
      type: object
      required:
        - id
        - date
        - round
        - homeTeam
        - awayTeam
        - complete
      properties:
        id:
          type: integer

        date:
          type: string
          format: date-time

        round:
          type: string

        homeTeam:
          type: string

        homeScore:
          type: integer
          nullable: true

        awayTeam:
          type: string

        awayScore:
          type: integer
          nullable: true

        complete:
          type: boolean

    MatchPredictions:
      type: object
      required:
        - id
        - match
        - predictions
      properties:
        id:
          type: integer

        match:
          $ref: "#/components/schemas/Match"
          
        predictions:
          type: array
          items:
            $ref: "#/components/schemas/Prediction"
    
    Prediction:
      type: object
      required:
        - id
        - participant
        - points
      properties:
        id:
          type: integer

        participant:
          type: string

        points:
          type: integer

        homeScore:
          type: integer

        awayScore:
          type: integer

        usedJoker:
          type: boolean


    Participant:
      type: object
      required:
        - name
        - predictions
        - tournamentPredictions
        - totalPoints

      properties:
        name:
          type: string

        predictions:
          type: array
          items:
            $ref: "#/components/schemas/Prediction"

        tournamentPredictions:
          $ref: "#/components/schemas/TournamentPredictions"

        totalPoints:
          type: integer

    TournamentPredictions:
      type: object
      required:
        - winner
        - runnerUp
        - thirdPlace
        - fourthPlace
        - topScorer
      
      properties:
        winner:
          type: string

        runnerUp:
          type: string
        
        thirdPlace:
          type: string

        fourthPlace:
          type: string

        topScorer:
          type: string


paths:
  /api/matches:
    get:
      operationId: getMatches
      summary: Get all matches
      responses:
        "200":
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Match"
              
  /api/matches/{id}:
    get:
      operationId: getMatch
      summary: Get a match with its predictions by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single match
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchPredictions"
        "400":
          description: Participant not found
  
  /api/participants:
    get:
      operationId: getParticipants
      summary: Get all participants
      responses:
        "200":
          description: List of participants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Participant"

  /api/participants/{name}:
    get:
      operationId: getParticipant
      summary: Get a participant by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single participant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Participant"
        "400":
          description: Participant not found
                  
