openapi: 3.0.3

info:
  title: World Cup Predictions API
  version: 1.0.0
  
components:
  schemas:
    Leaderboard:
      type: object
      required:
        - participant
        - totalPoints
        - position
        - previousPosition
        - correctScores
        - played
        - jokersPlayed
        - pointsDifference
        - correctResults
      properties:
        participant:
          type: string

        totalPoints:
          type: integer

        position:
          type: integer

        previousPosition:
          type: integer

        correctScores:
          type: integer
        
        played:
          type: integer

        jokersPlayed:
          type: integer

        pointsDifference:
          type: integer

        correctResults:
          type: integer

    Match:
      type: object
      required:
        - id
        - date
        - round
        - homeTeam
        - awayTeam
        - hasResult
      properties:
        id:
          type: integer

        date:
          type: string
          format: date-time

        round:
          type: string

        homeTeam:
          type: string

        homeScore:
          type: integer
          nullable: true

        awayTeam:
          type: string

        awayScore:
          type: integer
          nullable: true

        hasResult:
          type: boolean

    MatchNavigation:
      type: object
      required:
        - id
        - homeTeam
        - awayTeam
      properties:
        id:
          type: integer

        homeTeam:
          type: string

        awayTeam:
          type: string

    MatchPredictions:
      type: object
      required:
        - id
        - match
        - predictions
      properties:
        id:
          type: integer

        match:
          $ref: "#/components/schemas/Match"
          
        predictions:
          type: array
          items:
            $ref: "#/components/schemas/Prediction"

        previousNav:
          $ref: "#/components/schemas/MatchNavigation"

        nextNav:
          $ref: "#/components/schemas/MatchNavigation"
    
    Prediction:
      type: object
      required:
        - id
        - participant
        - points
        - homeScore
        - awayScore
        - hasResult
      properties:
        id:
          type: integer

        participant:
          type: string

        points:
          type: integer

        homeScore:
          type: integer

        awayScore:
          type: integer

        usedJoker:
          type: boolean

        hasResult:
          type: boolean

    Participant:
      type: object
      required:
        - name
        - predictions
        - tournamentPredictions
        - totalPoints

      properties:
        name:
          type: string

        predictions:
          type: array
          items:
            $ref: "#/components/schemas/Prediction"

        tournamentPredictions:
          $ref: "#/components/schemas/TournamentPredictions"

        totalPoints:
          type: integer

    TournamentPredictions:
      type: object
      required:
        - winner
        - runnerUp
        - thirdPlace
        - fourthPlace
        - topScorer
        - scorerNationality
      
      properties:
        winner:
          type: string

        runnerUp:
          type: string
        
        thirdPlace:
          type: string

        fourthPlace:
          type: string

        topScorer:
          type: string
        
        scorerNationality:
          type: string

    Team:
      type: object
      required:
        - displayName
        - code

      properties:
        displayName:
          type: string

        code:
          type: string

    ParticipantPrediction:
      type: object
      required:
        - participant
        - matchId
        - homeScore
        - awayScore

      properties:
        participant:
          type: string

        matchId:
          type: integer

        homeScore:
          type: integer

        awayScore:
          type: integer

        playedJoker:
          type: boolean


paths:
  /api/leaderboard:
    get:
      operationId: getLeaderboard
      summary: Get leaderboard
      responses:
        "200":
          description: The leaderboard
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Leaderboard"

  /api/matches:
    get:
      operationId: getMatches
      summary: Get all matches
      responses:
        "200":
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Match"
              
  /api/matches/{id}:
    get:
      operationId: getMatch
      summary: Get a match with its predictions and navigation information by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: A single match
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchPredictions"
        "400":
          description: Participant not found
  
  /api/participants:
    get:
      operationId: getParticipants
      summary: Get all participants
      responses:
        "200":
          description: List of participants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Participant"

  /api/participants/{name}:
    get:
      operationId: getParticipant
      summary: Get a participant by name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single participant
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Participant"
        "400":
          description: Participant not found

  /api/teams:
    get:
      operationId: getTeams
      summary: Get all teams
      responses:
        "200":
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Team"
                  
  /api/predictions:
    get:
      operationId: getPredictions
      summary: Get predictions (optionally filtered for match or participant)
      parameters:
        - name: matchId
          in: query
          required: false
          schema:
            type: integer
        - name: participant
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: List of predictions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Prediction"
          
    post:
      operationId: createPrediction
      summary: Enter a prediction for a participant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ParticipantPrediction"
      responses:
        "201":
          description: Prediction Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParticipantPrediction"
